######################################################################
# Automatically generated by qmake (3.0) Thu Oct 2 09:09:08 2014
######################################################################

TEMPLATE = app
TARGET = drawsquare
INCLUDEPATH += .
INCLUDEPATH += /usr/local/include/opencv2
LIBS += -lopencv_core -lopencv_highgui -lopencv_imgproc

# Input
SOURCES += square.cpp
